language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
    - PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
addons:
  apt:
    packages:
      - libgtk-3-dev
before_script:
    - WD="$PWD"
    - cd "$HOME"
    - curl -LO "https://github.com/gkoz/gtk-bootstrap/releases/download/gtk-3.18.1-2/deps.txz"
    - tar xf deps.txz
    - cd "$WD"
